<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ANITA" failures="0" tests="1" name="onlineTutorials.XMLResponseParsing" time="5.321" errors="1" timestamp="2024-02-13T18:33:03 GMT" skipped="0">
  <testcase classname="onlineTutorials.XMLResponseParsing" name="parseXmlUsingXmlPath" time="5.321">
    <error message="Failed to convert XML to Java Object. If you&#039;re trying convert to a list then use the getList method instead." type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Failed to convert XML to Java Object. If you're trying convert to a list then use the getList method instead.
at io.restassured.path.xml.XmlPath.getObjectAsType(XmlPath.java:403)
at io.restassured.path.xml.XmlPath.convertObjectTo(XmlPath.java:925)
at io.restassured.path.xml.XmlPath.getInt(XmlPath.java:444)
at onlineTutorials.XMLResponseParsing.parseXmlUsingXmlPath(XMLResponseParsing.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: groovy.lang.GroovyRuntimeException: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 16; The markup in the document following the root element must be well-formed.
at groovy.xml.XmlUtil.serialize(XmlUtil.java:458)
at groovy.xml.XmlUtil.serialize(XmlUtil.java:444)
at groovy.xml.XmlUtil.serialize(XmlUtil.java:191)
at groovy.xml.XmlUtil.serialize(XmlUtil.java:130)
at io.restassured.path.xml.XmlPath.getObjectAsType(XmlPath.java:401)
... 31 more
]]>
    </error>
  </testcase> <!-- parseXmlUsingXmlPath -->
  <system-out/>
</testsuite> <!-- onlineTutorials.XMLResponseParsing -->
